import forms from "@tailwindcss/forms";

/**
 * Design tokens from the Stitch project "AeroTwin Drone Engine Intelligence"
 * (design system "Precision Defense AeroTwin"), copied verbatim from the
 * tailwind.config embedded in its screen exports.
 * @type {import('tailwindcss').Config}
 */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d2d9f4",
        "surface-container-high": "#e2e7ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        outline: "#737688",
        primary: "#0047d3",
        "primary-container": "#1e5eff",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-container": "#7df5f4",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c5d9",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ab2",
        "tertiary-fixed": "#ffdbd0",
        "on-tertiary-fixed-variant": "#832700",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        tertiary: "#9c3000",
        error: "#ba1a1a",
        "on-surface": "#131b2e",
        surface: "#faf8ff",
        "on-surface-variant": "#434656",
        "surface-container": "#eaedff",
        "tertiary-container": "#c63f00",
        "inverse-primary": "#b6c4ff",
        "tertiary-fixed-dim": "#ffb59c",
        "on-secondary-fixed-variant": "#00504f",
        "surface-container-low": "#f2f3ff",
        "on-background": "#131b2e",
        "secondary-fixed": "#7df5f4",
        "surface-tint": "#004ee8",
        "on-primary-fixed": "#001550",
        "surface-container-highest": "#dae2fd",
        secondary: "#006a69",
        "on-primary-container": "#f0f0ff",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed": "#390c00",
        "on-secondary-fixed": "#002020",
        "on-secondary-container": "#007070",
        "secondary-fixed-dim": "#5ed9d7",
        "on-primary": "#ffffff",
        background: "#faf8ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-container": "#ffeeea",
        "on-error-container": "#93000a",
        "surface-bright": "#faf8ff",
        // Design-system prose tokens (designMd "Colors" + severity matrix).
        canvas: "#F5F7FA",
        hairline: "#E3E8EF",
        aviation: { DEFAULT: "#1E5EFF", hover: "#1748D1", active: "#143DAF", tonal: "#EEF4FF" },
        teal: { DEFAULT: "#0EA5A4", tonal: "#E6F8F8" },
        ink: { DEFAULT: "#0F172A", secondary: "#475569", muted: "#94A3B8" },
        sev: {
          normal: "#16A34A", "normal-bg": "#DCFCE7", "normal-text": "#15803D",
          watch: "#F59E0B", "watch-bg": "#FEF3C7", "watch-text": "#B45309",
          warning: "#EA580C", "warning-bg": "#FFEDD5", "warning-text": "#C2410C",
          critical: "#DC2626", "critical-bg": "#FEE2E2", "critical-text": "#B91C1C",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xl": "2rem",
        margin: "1.5rem",
        "margin-compact": "1rem",
        gutter: "1rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xs": "0.125rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "gutter-dense": "0.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "telemetry-sm": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "telemetry-md": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "telemetry-xl": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "telemetry-lg": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "telemetry-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-sm": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "telemetry-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "telemetry-xl": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "telemetry-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 1px 3px rgba(15, 23, 42, 0.05), 0 10px 15px -3px rgba(15, 23, 42, 0.03)",
        float: "0 20px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.04)",
      },
    },
  },
  plugins: [forms],
};
